apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 80