apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:9.4
        env:
        - name: POSTGRE_USER
          value: "postgres"
        - name: POSTGRE_PASSWORD
          value: "postgres"
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 5432
